[project]
name = "portfolio-backend-fastapi"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.116.1",
    "greenlet>=3.2.4",
    "passlib>=1.7.4",
    "psycopg-binary>=3.2.9",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.42",
]


[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "black>=25.1.0",
    "faker>=37.6.0",
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.8",
    "types-passlib>=1.7.7.20250602",
]


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 120
target-version = ["py313"]


[tool.isort]
profile = "black"


[tool.mypy]
disallow_untyped_defs = true
check_untyped_defs = true
disallow_any_generics = true
warn_redundant_casts = true
no_implicit_reexport = true
plugins = ['pydantic.mypy']
exclude = ['alembic/versions/', 'tests/']



[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.pytest.ini_options]
norecursedirs = ["db*", ".venv", ".*"]