"""Create ResourcePublicationModel

Revision ID: 41618ce357b6
Revises: f1646d7a85ab
Create Date: 2025-09-09 02:27:39.283259

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41618ce357b6"
down_revision: Union[str, Sequence[str], None] = "f1646d7a85ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_publications",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("publication_type", sa.Enum("ARTICLE", "CONFERENCE", name="publicationtypeenum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_publications")
    # ### end Alembic commands ###
