"""Create timeline and technology

Revision ID: 1b103b2fd75e
Revises: 8afa18e32f2e
Create Date: 2025-09-09 01:47:16.324607

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b103b2fd75e"
down_revision: Union[str, Sequence[str], None] = "8afa18e32f2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_technologies",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_work_timeline_items",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("start_year", sa.BIGINT(), nullable=False),
        sa.Column("end_year", sa.BIGINT(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association_resource_work_timeline_item_resource_technology",
        sa.Column("technology_id", sa.BIGINT(), nullable=False),
        sa.Column("work_timeline_id", sa.BIGINT(), nullable=False),
        sa.Column("weight", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["resource_technologies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_timeline_id"],
            ["resource_work_timeline_items.id"],
        ),
        sa.PrimaryKeyConstraint("technology_id", "work_timeline_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association_resource_work_timeline_item_resource_technology")
    op.drop_table("resource_work_timeline_items")
    op.drop_table("resource_technologies")
    # ### end Alembic commands ###
