"""Create ResourceEducationTimelineItemModel

Revision ID: f1646d7a85ab
Revises: 1b103b2fd75e
Create Date: 2025-09-09 02:16:27.401677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1646d7a85ab'
down_revision: Union[str, Sequence[str], None] = '1b103b2fd75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_education_timeline_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('place', sa.String(length=256), nullable=False),
    sa.Column('start_year', sa.BIGINT(), nullable=False),
    sa.Column('end_year', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_resource_education_timeline_item_technology',
    sa.Column('technology_id', sa.BIGINT(), nullable=False),
    sa.Column('education_timeline_id', sa.BIGINT(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['education_timeline_id'], ['resource_education_timeline_items.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['resource_technologies.id'], ),
    sa.PrimaryKeyConstraint('technology_id', 'education_timeline_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_resource_education_timeline_item_technology')
    op.drop_table('resource_education_timeline_items')
    # ### end Alembic commands ###
