"""Add association between user and role

Revision ID: 38de360fafba
Revises: e8ccac056c64
Create Date: 2025-09-03 02:39:39.852105

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38de360fafba"
down_revision: Union[str, Sequence[str], None] = "e8ccac056c64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_role_association",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("role_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["roles.role_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("user_uuid", "role_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role_association")
    # ### end Alembic commands ###
