"""Add resourse skill model

Revision ID: 76d2cde562b1
Revises: 1eae187666f2
Create Date: 2025-09-03 02:04:24.826948

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76d2cde562b1"
down_revision: Union[str, Sequence[str], None] = "1eae187666f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resourse_skills",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("weight", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resourse_skills")
    # ### end Alembic commands ###
