"""Renamae table rouserce skill

Revision ID: 8afa18e32f2e
Revises: f834eb5ebd8f
Create Date: 2025-09-07 22:20:58.761042

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8afa18e32f2e"
down_revision: Union[str, Sequence[str], None] = "f834eb5ebd8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_skills",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("weight", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("resourse_skills")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resourse_skills",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("weight", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("resourse_skills_pkey")),
    )
    op.drop_table("resource_skills")
    # ### end Alembic commands ###
