"""Add email field to user model

Revision ID: d16b8c00b1ee
Revises: 2d9ae12a6477
Create Date: 2025-08-10 22:20:55.653922

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d16b8c00b1ee"
down_revision: Union[str, Sequence[str], None] = "2d9ae12a6477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email")
    # ### end Alembic commands ###
