"""Rename users table name

Revision ID: e8ccac056c64
Revises: b465a49848cd
Create Date: 2025-09-03 02:39:15.408135

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8ccac056c64"
down_revision: Union[str, Sequence[str], None] = "b465a49848cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("user_uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_uuid", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "email", name=op.f("user_email_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
        sa.UniqueConstraint(
            "username", name=op.f("user_username_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
