"""Fix role association name

Revision ID: f834eb5ebd8f
Revises: 38de360fafba
Create Date: 2025-09-03 02:56:32.385510

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f834eb5ebd8f"
down_revision: Union[str, Sequence[str], None] = "38de360fafba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
