"""Alter email field

Revision ID: fd0f5244a316
Revises: d16b8c00b1ee
Create Date: 2025-08-10 22:24:01.285434

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd0f5244a316"
down_revision: Union[str, Sequence[str], None] = "d16b8c00b1ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=256), nullable=True)
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###
