name: "Lint"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [ 'mypy', 'flake8', 'black' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install deps
        run: uv sync

      - name: Run ${{ matrix.linter }}

        run: |
          if [ "${{ matrix.linter }}" = "mypy" ]; then
            uv run mypy src/
          elif [ "${{ matrix.linter }}" = "flake8" ]; then
            uv run flake8 src/
          elif [ "${{ matrix.linter }}" = "black" ]; then
            uv run black --check src/
          fi