name: "Pytest"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Start db
        run: docker-compose up -d db

      - name: Install deps
        run: uv sync

      - name: cp .env
        run: cp .env.example .env

      - name: Source environment
        run: source .env
      - name: Run tests
        run:  uv run pytest


